# Generated by Django 4.1.7 on 2023-06-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_news_options_news_banner_alter_news_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
