# Generated by Django 4.2.2 on 2023-06-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='banner',
            field=models.ImageField(upload_to='images/', verbose_name='Imagen Banner'),
        ),
    ]
